import type { Metadata } from "next";
import "./globals.css";
import RecoilRootWrapper from "./RecoilRootWrapper";

export const metadata: Metadata = {
  title: "sendback",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RecoilRootWrapper>
        <body>{children}</body>
      </RecoilRootWrapper>
    </html>
  );
}
